### ISSUE TITLE
Old versions fail with new updates

### ISSUE THREAD

**Issue by capodilupod** [mailslurp/swagger-sdk-typescript-fetch#1]
It seems when updates are being pushed out, older versions of mailslurp are failing. This is the second time this has happened to me after a push has gone out. Got this error 

```js
error Couldn't find match for "2a57fd0e84e74f8a3933c092f10bdf0d5d940923" in "refs/heads/master" for "https://github.com/mailslurp/swagger-sdk-typescript-fetch.git".
```

It appears that commits are being deleted when new updates are pushed out. Not always noticed on local development either unless I clear my yarn cache and then upgrade the package.

**Comment by jackmahoney** [comment]
Very sorry for this.

Please see explanation here: https://github.com/mailslurp/mailslurp-client-ts-js/issues/11

**Comment by jackmahoney** [comment]
Issue is now resolved and the github dependency has been completely removed.
